### ISSUE TITLE
Aggregate Ski Statistics : Season Total

### ISSUE THREAD

**Issue by Vaibhav2399** [rilling/OpenTracks-Winter-SOEN-6431_2024#102]
**Describe briefly your feature.**
This feature introduces a comprehensive way to visualize season totals within our application. It aims to highlight some important season statistics by displaying the following metrics:

Total Number of Days: The total days the individual used our app to track their runs.
Total Number of Runs: The total count of runs taken by an individual during a season.
Total Distance Covered (in KM): The total distance covered by the individual through their runs.
Total Vertical Distance (in M): The total meters of vertical distance covered by the user.
Total Active Time (hh:mm:ss): Total time the user used our app for tracking their runs.
Number of Resorts: Count of resorts taken throughout the season. 

**Describe the solution you'd like**
To introduce this functionality, we'll compute the combined values for all the specified metrics. Utilizing the user's past data saved in our database, these computations will be generated. Afterward, we'll dynamically showcase these results on the user interface, ensuring they're readily accessible and visually appealing.

**Describe alternatives you've considered**
We can have charts and graphs to display the data on the UI
Comparing user achievements with their previous season results to get a better overview of their performance.

**Additional context**
<img width="388" alt="image" src="https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/assets/33949659/88f228b0-3057-40a6-aec0-5474959b45b5">

**Comment by mmobbu** [comment]
Calculated the season totals for the features mentioned above and below is the output.
![WhatsApp Image 2024-04-07 at 9 54 37 PM](https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/assets/145586759/c73e09e1-3cc4-42f8-80fe-1d1b958582f8)
