### ISSUE TITLE
Aggregate Ski Statistics : Season Best

### ISSUE THREAD

**Issue by Vaibhav2399** [rilling/OpenTracks-Winter-SOEN-6431_2024#105]
**Describe briefly your feature.**
This feature introduces a comprehensive way to visualize key achievements within our application. It aims to highlight personal bests and significant milestones by displaying the following metrics:

Maximum Distance Covered: The greatest distance (in kilometers) achieved in a single run, along with the date this occurred.
Highest Elevation Gain: The run with the highest elevation gain, specifying the total elevation and the date.
Longest Run Duration: The longest time spent on a single run, including the distance covered and the date.
Most Runs in a Day: The highest number of runs completed in a single day, with the date no

**Describe the solution you'd like**
To implement this feature, we'll calculate the aggregate values for each of the mentioned metrics. These calculations will be based on the user's historical data stored in our database. Once computed, we will dynamically display these values on the user interface, ensuring they're easily accessible and visually engaging for the user.

**Describe alternatives you've considered**
We can have charts and graphs to display the data on the UI
Comparing user achievements with those of their peers or within their community for added motivation.

**Comment by apoorva2404** [comment]
Closing this issue after developing and merging the code
