### ISSUE TITLE
Button UI changes for recording

### ISSUE THREAD

**Issue by SizzlingHot** [rilling/OpenTracks-Winter-SOEN-6431_2024#107]
**Description**

- On the main page of the app, the start/stop button for starting a recording of an exercise is currently not intuitive.
- While recording, there should be a pause and stop button available for the user
- A resume or stop button should appear when the pause button has been pressed

**Solution**

- Add a new, more intuitive start/stop button to the app.
- Add a new pause button along with adjusted stop button once the recording has started.
- Add new resume and stop button for the new pause feature.

**Additional context**

Picture of where the feature will be changed
![image](https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/assets/58235475/2886eeef-e089-4bf1-a73d-69c14262b54d)

Buttons to add to the app
![image](https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/assets/58235475/f6e7a64f-447a-4469-abc2-a7fb298be23a)![image](https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/assets/58235475/69999a77-5f00-4264-a09a-7dc1b7ee2e72)![image](https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/assets/58235475/7c252d2d-9afe-4fb7-9272-dfe062345384)![image](https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/assets/58235475/3e24efa9-de83-4e23-8569-fb5a5c8e3d20)

**Comment by daivik1515** [comment]
Added the start, stop, pause button by adding the image buttons in tracklist.xml, trackrecorded.xml . Updated the trackRecordingActivity and trackListActivity files. 
[Commit for issue #107](https://github.com/gup-abhi/OpenTracks-Winter-SOEN-6431_2024/commit/db2a37c985766fc53fd076465bd55d5077311272)

**Comment by daivik1515** [comment]
fixed the track_recording.xml file to update the pause button. [Commit for issue #107](https://github.com/gup-abhi/OpenTracks-Winter-SOEN-6431_2024/commit/bc888771b0e40d2bc976d51c190e6ed360b8bbe9)
