### ISSUE TITLE
Settings (Voice Announcements) - Announce for total time skied at End of the recording.

### ISSUE THREAD

**Issue by arshdeepsinghofficial** [rilling/OpenTracks-Winter-SOEN-6431_2024#116]
**Feature Description**

This feature aims to enhance the user experience by providing voice announcements for the total time skied at the end of a recording session in the settings menu.

**Solution**

- Option in settings menu: "Voice Announcements"
- Sub-option for "Total Time Skied"
- Enable/disable toggle for announcements
- Triggered at end of recording session
- System announces total skiing duration

**Alternatives**

- One alternative is to implement a visual notification instead of or in addition to voice announcements. This could be in the form of a pop-up message or a banner displayed on the screen at the end of the recording session. 

**Additional context**

This feature would be particularly useful for skiers who prefer auditory feedback during their sessions or for those who may not be able to easily view their device screens while skiing. By providing voice announcements for key metrics like total time skied, users can stay informed and track their progress more effectively.

**Comment by HWJFish** [comment]
https://github.com/HWJFish/OpenTracks-Winter-SOEN-6431_2024/pull/9

**Comment by arshdeepsinghofficial** [comment]
Development completed and featured implemented.
