### ISSUE TITLE
Settings (Voice Announcements) - Announce for temperature at End of the recording.

### ISSUE THREAD

**Issue by arshdeepsinghofficial** [rilling/OpenTracks-Winter-SOEN-6431_2024#117]
**Feature Description**

The feature involves incorporating a setting within the application's settings menu, to enable automated announcements of the temperature at the conclusion of a recording session.

**Solution**

- Add a new option titled "Temperature Announcements" under the "Voice Announcements" section in the settings menu.
- Include a toggle switch to allow users to enable or disable temperature announcements.
- Upon completion of a recording session, if the feature is enabled, the system will audibly announce the temperature.

**Alternatives**

- Implementing a manual request feature where users can trigger a voice announcement of the current temperature .
- Option to customize when temperature announcements occur, such as after specific time intervals or at the beginning/end of a session.

**Additional context**

- Including temperature announcements can enhance user experience, especially for outdoor activities where temperature changes may affect conditions.
- Users may find this feature useful for monitoring weather conditions during their activities without needing to check their devices manually.

**Comment by umang232** [comment]
The issue has been successfully completed
