### ISSUE TITLE
General GUI Improvements-Automatically discard records 

### ISSUE THREAD

**Issue by racCC** [rilling/OpenTracks-Winter-SOEN-6431_2024#125]
**Description**

- The feature enables the automatic discard of exercise records based on predefined or custom time thresholds.
- Users can select from three default settings (5 seconds, 10 seconds, 20 seconds) or specify a custom length in seconds.
- This functionality helps users maintain a clean and relevant record of their exercise activities by filtering out short or insignificant entries.

**Proposed Solution**

- Implement a toggle switch in the application settings to enable or disable the automatic record discard feature.
- When enabled, present users with options to choose from the default settings or specify a custom length for the minimum duration of exercise records to be retained.
- Automatically discard exercise records with a duration shorter than the specified threshold.

**Alternatives**

- Manual filtering option: Users manually select and delete individual exercise records, but this could be cumbersome for large datasets.
- Criteria-based discard: Discard records based on criteria like exercise intensity or type, but may not accurately reflect user preferences based on time duration.

**Additional context**
Screenshot of the page where changes will be made

![WhatsApp Image 2024-03-17 at 2 19 04 PM](https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/assets/32578834/0d6e10fa-1201-4ff4-9a2c-d4b2d00cb8f2)

**Comment by gup-abhi** [comment]
"Automatically discard records" feature has been successfully implemented and merged into the main repository. This enhancement allows users to automatically discard exercise records below a specified length, enhancing data quality and improving the user experience.
