### ISSUE TITLE
Statistics (service functions, Ski statistics) - Total travel time on chairlift including waiting time

### ISSUE THREAD

**Issue by katrodiyaarchil** [rilling/OpenTracks-Winter-SOEN-6431_2024#134]
**Describe briefly your feature.**
The feature aims to accurately calculate the total travel time on chairlifts, including waiting time, to provide users with precise data regarding their skiing sessions.

**Describe the solution you'd like**
We need to review and potentially refactor the existing implementation for calculating total travel time on chairlifts. This involves:

- Ensuring accurate identification of user entry and exit from chairlifts.

- Proper segmentation to determine when users are on chairlifts.

- Accurate measurement of waiting times at chairlifts.

- Calculation of total travel time, with the addition of travel time on chairlifts and waiting time.

**Additional context**
This feature can help users analyze their skiing accurately with precision.

**Comment by beingtranquil** [comment]
Hello, I am from group 9, I need your feature for my part of implementation. Can I get an estimated time for the completion of your part? Thank you.

**Comment by mkjodhani** [comment]
@JayPatel286  This issue overrides with #62, which was created before this issue.Please kindly look into it. And also it has been merged.
