### ISSUE TITLE
Adding a new feature - Chairlift efficiency rating

### ISSUE THREAD

**Issue by dneha1210** [rilling/OpenTracks-Winter-SOEN-6431_2024#135]
**Describe briefly your feature.**
The chairlift efficiency rating feature aims to assess the operational efficiency of chairlifts by analyzing key performance indicators such as waiting times, travel times, and overall user satisfaction. This metric is valuable for users to select the best of the chairlifts, they have travelled with.

**Describe the solution you'd like**
Implement an algorithm within the app that collect and analyze real-time data on chairlift performance, including wait times, ride durations. By aggregating and analyzing this data, the app will generate efficiency ratings for each chairlift, allowing users to make informed decisions about which chairlifts to use based on factors such as speed, reliability, and user experience.

**Describe alternatives you've considered**
 One alternative we considered was to rely solely on user feedback to rate chairlift efficiency. However, this approach may be subjective and prone to bias, as users' experiences can vary based on factors such as time of day, weather conditions, and personal preferences.

**Additional context**
Efficient chairlift operations are essential for optimizing the user experience and maximizing user satisfaction. Integrating this feature into the app will differentiate it from competitors and provide users with a valuable tool for planning their activities.

**Comment by SrujithaYeruva** [comment]
We have added two new features which can be added to calculate average distance and speed between two track points to fix the issue. 
Links to the PR's created for fixing this issue:
[170](https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/pull/170)
[180](https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/pull/180)
