### ISSUE TITLE
Statistics (service functions, Ski statistics)- Calculate average speed

### ISSUE THREAD

**Issue by AishwaryaShinde07** [rilling/OpenTracks-Winter-SOEN-6431_2024#55]
**Description of the feature**
Calculate average Speed based on the data.
Adding a feature to calculate a skier's average speed during their runs, enhancing the OpenTracks app with vital stats for performance tracking

**Describe the solution you'd like**
Create a function to calculate Average speed.  This data will be provided for the OSM Dashboard.
The app will use GPS data to calculate and display the average speed for each ski run, excluding inactive periods, and present this in the session summary.

**Describe alternatives you've considered**
We've considered manual time entry for start/stop runs and using accelerometer data as alternatives to GPS.

**Additional context**
Accuracy in mountainous areas is crucial; hence, the feature will include GPS data smoothing techniques and comply with the app's offline, privacy-centric design.

**Comment by beingtranquil** [comment]
Hello, I am from group 9 and I wanted to know the estimated time for this to complete because I am going to need this feature for my part as well. Thank you.

**Comment by AishwaryaShinde07** [comment]
> Hello, I am from group 9 and I wanted to know the estimated time for this to complete because I am going to need this feature for my part as well. Thank you.

I have added the changes

**Comment by Sharanyu** [comment]
Hi @AishwaryaShinde07,
I checked for Run.java and changes in RunAnalyzer.java file I could not find it in the main repository also any changes you have made. We need this for issue : #69  , Please let us know (from Group 9).

**Comment by beingtranquil** [comment]
I am also from group 9, the changes that you have made are limited to your forked branch and we cannot access it.

**Comment by AishwaryaShinde07** [comment]
> I am also from group 9, the changes that you have made are limited to your forked branch and we cannot access it.

I am not able to merge changes in main branch due to the conflict of some files of my other teammates so you can try taking the fork branch from our branch to access the code and the main logic of average speed code is in RunAnalyzer.java
