### ISSUE TITLE
Statistics (service functions, Ski statistics) - Total Travel Time Calculation for Chairlifts

### ISSUE THREAD

**Issue by mkjodhani** [rilling/OpenTracks-Winter-SOEN-6431_2024#62]
**Describe briefly your feature.**
The feature aims to accurately calculate the total travel time on chairlifts, to provide users with precise data regarding their skiing sessions.

**Describe the solution you'd like**
We need to review and potentially refactor the existing implementation for calculating total travel time on chairlifts. This involves:

1. Ensuring accurate identification of user entry and exit from chairlifts.
2. Proper segmentation to determine when users are on chairlifts.
3. Accurate measurement of waiting times at chairlifts.
4. Calculation of total travel time, including both travel time on chairlifts and waiting time.

**Describe alternatives you've considered**
An alternative approach could involve using additional sensors or technologies to track user movement more accurately. However, this may introduce complexity and cost implications.

**Additional context**
This issue is crucial for enhancing the overall user experience and providing users with reliable data for analyzing their skiing sessions.

**Solution**

Added following function as a part of proposed solution.

<img width="1224" alt="image" src="https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/assets/47267142/8bbdcb4a-5446-45bd-81ad-134122d7e94f">

**Comment by beingtranquil** [comment]
Hello, I am from group 9, I wanted to know if you have completed your part because I will need your part for my implementation. Thank you.

**Comment by mkjodhani** [comment]
I have finished the task and will merge the PR

**Comment by beingtranquil** [comment]
Okay thank you. and just to clarify, this function would calculate the total travel time for the whole day right? or it is just for a single run?

**Comment by mkjodhani** [comment]
it will calculate the time for previous ride.

**Comment by mkjodhani** [comment]
@beingtranquil, you can access the functionality from the main branch. I have merge this PR, as the requirements were blocking. 
PLease let me know if anything is needed.

**Comment by beingtranquil** [comment]
Okay thank you so much.

**Comment by beingtranquil** [comment]
Sorry is this the time spent on chairlifts only? or also the waiting time?

**Comment by mkjodhani** [comment]
No, the waiting is associated with issue #60.

**Comment by mkjodhani** [comment]
@JayPatel286 You can include the waiting as a part of your Issue.
