### ISSUE TITLE
Statistics (aggregate per day (run/lift) - Average % Slope

### ISSUE THREAD

**Issue by beingtranquil** [rilling/OpenTracks-Winter-SOEN-6431_2024#68]
**Describe briefly your feature.**
This feature is for including the UI element to display Average % Slope.

**Describe the solution you'd like**
We will take the "slope %" method's outcome from Group 4-6  -  Statistics (service functions, Ski statistics) and make this this UI element visible.

**Describe alternatives you've considered**
There is no alternative solution for this.

**Comment by OmniaAlam** [comment]
Related issue: https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/issues/54
