### ISSUE TITLE
Statistics (aggregate per day (ski/chairlift) - Total Skied km 

### ISSUE THREAD

**Issue by nihal514** [rilling/OpenTracks-Winter-SOEN-6431_2024#72]
**Describe briefly your feature.**
This feature is used to implement UI element to display total skied kilometers aggregated per day. It depends on the functionality developed by Groups# 4 - 6, related issue link #59.

**Describe the solution you'd like**
Group number # 4-6 works on the methods for creating the statistics(service functions, Ski statistics) and this function is provides with the total skied km. Once this method is created, the code to find the aggregate data per day can be added which will in turn be used by the xml file which can be modified with required attributes to display the Total skied kilometers .

**Describe alternatives you've considered**
When aforementioned method  doesn't work then there can be one alternative like user can manually add total skied km and with the help of that data i can aggregate total kilometers per day but this is not a trustworthy as this data is inaccurate.

**Additional context**
![WhatsApp Image 2024-03-17 at 18 17 15](https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/assets/62697635/4db52b18-50fa-45e4-9ea8-5fe4b367dd39)

**Comment by beingtranquil** [comment]
Hi Nihal, I wanted to know the status of your code, because I am not able to find a way to access track points. Please ping me if you are able to do so
