### ISSUE TITLE
Statistics - Aggregate Per Day (Ski/ChairLift) - Longest Wait at Ski Chairlift

### ISSUE THREAD

**Issue by ushnish2001** [rilling/OpenTracks-Winter-SOEN-6431_2024#79]
Description:
This feature is aimed at implementing a UI component to showcase the longest wait time at the ski chairlift, aggregated daily.

Proposed Solution:
 Groups # 4-6 concentrates on developing methods for generating statistics (e.g., service functions, Ski statistics). Once these methods are established, additional code can be integrated to compute aggregate data per day. The computed data will then be utilized by an XML file, configurable with necessary attributes to present the longest wait time at the ski chairlift.

Alternative Considerations:
If the initial approach proves ineffective, an alternative involves enabling users to manually input wait times at the ski chairlift. However, this method may be less reliable due to potential inaccuracies in user-provided data.

Additional Context:
![WhatsApp Image 2024-03-17 at 18 17 15](https://github.com/rilling/OpenTracks-Winter-SOEN-6431_2024/assets/62697635/5056af59-7be7-4bb1-901a-9679fcc36198)

**Comment by YugKotak** [comment]
Implemented Longest Wait at Ski Chairlift
